### ISSUE TITLE
The self.level_embed paramter is never used

### ISSUE THREAD

**Issue by timmeinhardt** [PRBonn/MaskPLS#13]
Your `MaskedTransformerDecoder` never applies the level encoding during the forward pass. Was this intentionally?

**Comment by rmarcuzzi** [comment]
Hi!
We don't use it, we just forgot to remove it from the code.

**Comment by timmeinhardt** [comment]
Did you ablate whether adding/removing the level encoding has an effect on the performance?

**Comment by rmarcuzzi** [comment]
In our early experiments, adding it didn't change the performance but we didn't check in the final model.
