### ISSUE TITLE
Softmax for Class Probabilities in Panoptic Inference Function

### ISSUE THREAD

**Issue by YilmazKadir** [PRBonn/MaskPLS#2]
Thank you for publishing your code. I wanted to ask if there is a small mistake in this line:
https://github.com/PRBonn/MaskPLS/blob/f80691232bd25183435fd28dc54026652c209627/mask_pls/models/mask_model.py#LL135C35-L135C35
I believe you should apply a softmax function to get the probabilities similar to what you do in the semantic inference function:
https://github.com/PRBonn/MaskPLS/blob/f80691232bd25183435fd28dc54026652c209627/mask_pls/models/mask_model.py#LL119C16-L119C16
Am I missing something or is there a slight mistake?

**Comment by rmarcuzzi** [comment]
Hi!
You can apply the `softmax()` function and then `argmax()` to obtain the class probabilities but you can also directly use `argmax()`.
We empirically found that not using the `softmax()` yielded a slightly better performance. You can try adding it and evaluating and you'll see the difference.
