### ISSUE TITLE
Visualization results in error

### ISSUE THREAD

**Issue by mofarazi** [PRBonn/MaskPLS#4]
Hi, I get the following error:

> Using semantics in visualizer
> Using instances in visualizer
> Points shape:  (127405, 3)
> Label shape:  (126576,)
> Traceback (most recent call last):
>   File "visualize.py", line 185, in <module>
>     vis = LaserScanVis(scan=scan,
>   File "/home/mfarazi/Mohammad/vis_semantic_kitti/semantic-kitti-api/auxiliary/laserscanvis.py", line 31, in __init__
>     self.update_scan()
>   File "/home/mfarazi/Mohammad/vis_semantic_kitti/semantic-kitti-api/auxiliary/laserscanvis.py", line 137, in update_scan
>     self.scan.open_label(self.label_names[self.offset])
>   File "/home/mfarazi/Mohammad/vis_semantic_kitti/semantic-kitti-api/auxiliary/laserscan.py", line 235, in open_label
>     self.set_label(label)
>   File "/home/mfarazi/Mohammad/vis_semantic_kitti/semantic-kitti-api/auxiliary/laserscan.py", line 251, in set_label
>     raise ValueError("Scan and Label don't contain same number of points")
> ValueError: Scan and Label don't contain same number of points

I have debugged the code and found at that in semanticdataset class, there is a **keep** mask that removes some points and eventually these label files and original point cloud do not match is size. How did you visualize the results? I used the semantic-kitti-api from PRBonn.

**Comment by rmarcuzzi** [comment]
Hi! 
To visualize your results, you could just comment out that part to have the same number of points and labels.
On the other hand, you could use a library like Open3D to create a point cloud and use the color_map from the sematic-kitti.yaml file to add the colors.
I hope this helps!
I'll close the issue but feel free to reopen it if necessary!
