### ISSUE TITLE
How to test a point cloud or a set of points prepared by myself?

### ISSUE THREAD

**Issue by KkCabin** [PRBonn/MaskPLS#9]
Hi,

Thank you for your outstanding work. I have a question, how can I test the results on my own dataset? For example, input a point cloud or a set of point clouds and store the results after instances segmentation

**Comment by rmarcuzzi** [comment]
Hi!
You should create a dataloader to load the points and intensities following the [SemanticDataset](https://github.com/PRBonn/MaskPLS/blob/main/mask_pls/datasets/semantic_dataset.py#L115) class.
Once you can run your forward pass loading the weights, you'll have the semantic and instance predictions for each input point in the [test step](https://github.com/PRBonn/MaskPLS/blob/main/mask_pls/models/mask_model.py#L95).

**Comment by KkCabin** [comment]
> Hi!
> You should create a dataloader to load the points and intensities following the [SemanticDataset](https://github.com/PRBonn/MaskPLS/blob/main/mask_pls/datasets/semantic_dataset.py#L115) class.
> Once you can run your forward pass loading the weights, you'll have the semantic and instance predictions for each input point in the [test step](https://github.com/PRBonn/MaskPLS/blob/main/mask_pls/models/mask_model.py#L95).

Ok, thank you for your response😊. I'll have a try.
